# Generated by Django 5.2 on 2026-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0038_notificationchannelsettings_notificationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, null=True),
        ),
    ]
