# Generated by Django 5.2 on 2026-05-18 07:54

import django.db.models.deletion
import jobapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0039_adminprofile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('phone_verification', models.BooleanField(default=False)),
                ('domain_restriction', models.BooleanField(default=False)),
                ('allowed_domains', models.JSONField(blank=True, default=jobapp.models.JobseekerPlatformSettings.default_allowed_domains)),
                ('default_role', models.CharField(default='Job Seeker', max_length=100)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('Public', 'Public'), ('Employers Only', 'Employers Only'), ('Private', 'Private')], default='Employers Only', max_length=50)),
                ('resume_visibility', models.CharField(choices=[('Public', 'Public'), ('Employers Only', 'Employers Only'), ('Private', 'Private')], default='Employers Only', max_length=50)),
                ('anonymous_profile', models.BooleanField(default=False)),
                ('profile_completion_required', models.CharField(default='0 %', max_length=20)),
                ('salary_visibility', models.BooleanField(default=True)),
                ('company_reviews', models.BooleanField(default=True)),
                ('application_status_tracking', models.BooleanField(default=True)),
                ('similar_jobs', models.BooleanField(default=True)),
                ('career_advice', models.BooleanField(default=True)),
                ('easy_apply', models.BooleanField(default=True)),
                ('save_jobs', models.BooleanField(default=True)),
                ('max_applications', models.PositiveIntegerField(default=30)),
                ('application_expiry_days', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adminquiethours',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', '(UTC +05:30) Asia/Kolkata'), ('America/Los_Angeles', '(UTC -08:00) America/Los_Angeles'), ('UTC', '(UTC +00:00) UTC'), ('Europe/London', '(UTC +01:00) Europe/London'), ('Europe/Berlin', '(UTC +02:00) Europe/Berlin')], default='Asia/Kolkata', max_length=100),
        ),
        migrations.CreateModel(
            name='EmployerPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('mobile_verification', models.BooleanField(default=False)),
                ('approval_type', models.CharField(choices=[('Manual Type', 'Manual Type'), ('Automatic', 'Automatic')], default='Manual Type', max_length=20)),
                ('req_company_cert', models.BooleanField(default=False)),
                ('req_gst_cert', models.BooleanField(default=False)),
                ('req_business_email', models.BooleanField(default=False)),
                ('req_company_website', models.BooleanField(default=False)),
                ('allow_multiple_company', models.BooleanField(default=False)),
                ('allow_multiple_users', models.BooleanField(default=False)),
                ('show_company_reviews', models.BooleanField(default=False)),
                ('enable_company_branding', models.BooleanField(default=False)),
                ('featured_employer_option', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=False)),
                ('notif_new_signups', models.BooleanField(default=False)),
                ('notif_alerts', models.BooleanField(default=False)),
                ('notif_announcements', models.BooleanField(default=False)),
                ('notif_weekly_summary', models.BooleanField(default=False)),
                ('job_expire_days', models.PositiveIntegerField(default=30)),
                ('max_job_posts', models.PositiveIntegerField(default=10)),
                ('featured_job_limit', models.PositiveIntegerField(default=3)),
                ('allow_edit_after_approval', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('Pending approval', 'Pending approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending approval', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_settings', to='jobapp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('inapp', 'In App'), ('push', 'Push'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='jobapp.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
